defmodule Sidecar.Config do
  @moduledoc """
  Runtime configuration for the planck_docker bundled sidecar.

  Values are resolved by Skogsra from (highest priority first):

  1. Environment variables
  2. Application config (`config :sidecar, ...`)
  3. Hardcoded defaults

  | Key | Env var | Default |
  |---|---|---|
  | `workspace_dir` | `WORKSPACE_DIR` | `/workspace` |
  | `searxng_url` | `SEARXNG_URL` | `http://searxng:8080` |
  | `typesense_url` | `TYPESENSE_URL` | `http://typesense:8108` |
  | `typesense_api_key` | `TYPESENSE_API_KEY` | `planck-internal-key` |
  | `typesense_collection` | `TYPESENSE_COLLECTION` | `workspace` |
  | `sessions_collection` | `TYPESENSE_SESSIONS_COLLECTION` | `long_term_memory` |
  | `memory_collection` | `TYPESENSE_MEMORY_COLLECTION` | `short_term_memory` |
  | `tika_url` | `TIKA_URL` | `http://tika:9998` |
  | `agent_vault_url` | `AGENT_VAULT_URL` | `nil` |
  | `agent_vault_token` | `AGENT_VAULT_TOKEN` | `nil` |
  | `agent_vault_vault` | `AGENT_VAULT_VAULT` | `"planck"` |
  """
  use Skogsra

  @envdoc "Absolute path to the mounted workspace directory."
  app_env :workspace_dir, :sidecar, :workspace_dir,
    os_env: "WORKSPACE_DIR",
    default: "/workspace"

  @envdoc "Base URL of the Typesense instance (internal Docker service)."
  app_env :typesense_url, :sidecar, :typesense_url,
    os_env: "TYPESENSE_URL",
    default: "http://typesense:8108"

  @envdoc "API key for the Typesense instance."
  app_env :typesense_api_key, :sidecar, :typesense_api_key,
    os_env: "TYPESENSE_API_KEY",
    default: "planck-internal-key"

  @envdoc "Base URL of the Searxng instance (internal Docker service)."
  app_env :searxng_url, :sidecar, :searxng_url,
    os_env: "SEARXNG_URL",
    default: "http://searxng:8080"

  @envdoc "Name of the Typesense collection used for workspace file indexing."
  app_env :typesense_collection, :sidecar, :typesense_collection,
    os_env: "TYPESENSE_COLLECTION",
    default: "workspace"

  @envdoc "Name of the Typesense collection used for long-term session turn indexing."
  app_env :sessions_collection, :sidecar, :sessions_collection,
    os_env: "TYPESENSE_SESSIONS_COLLECTION",
    default: "long_term_memory"

  @envdoc "Name of the Typesense collection used for short-term agent memory (prompt injection)."
  app_env :memory_collection, :sidecar, :memory_collection,
    os_env: "TYPESENSE_MEMORY_COLLECTION",
    default: "short_term_memory"

  @envdoc "Base URL of the Apache Tika Server instance (internal Docker service)."
  app_env :tika_url, :sidecar, :tika_url,
    os_env: "TIKA_URL",
    default: "http://tika:9998"

  @envdoc """
  Base URL of the agent-vault management API (e.g. `http://vault:14321`).
  When set, `Sidecar.Secrets.AgentVault` uses this to store and retrieve
  credentials and manage service rules.
  """
  app_env :agent_vault_url, :sidecar, :agent_vault_url,
    os_env: "AGENT_VAULT_URL",
    default: nil

  @envdoc """
  Scoped agent token for agent-vault. Generated by the setup container on
  first run and passed through by `SidecarManager` from the headless process
  environment. Used as a Bearer token on all vault API calls.
  """
  app_env :agent_vault_token, :sidecar, :agent_vault_token,
    os_env: "AGENT_VAULT_TOKEN",
    default: nil

  @envdoc "Name of the vault used for Planck secrets and service rules."
  app_env :agent_vault_vault, :sidecar, :agent_vault_vault,
    os_env: "AGENT_VAULT_VAULT",
    default: "planck"
end
